---
title: "Homer Theme"
subtitle: "Walkx"
logo: "logo.png"

header: false
footer: '<p>Theme made with <span class="has-text-danger">❤️</span> by <a href="https://github.com/WalkxCode">Walkx</a></p>' # Set false if you want to hide it.

stylesheet:
  - "assets/custom.css"

columns: "3" # You can change this to any number that is a factor of 12: (1, 2, 3, 4, 6, 12)
theme: default
colors:
  light:
    highlight-primary: "#fff5f2"
    highlight-secondary: "#fff5f2"
    highlight-hover: "#bebebe"
    background: "#12152B"
    card-background: "rgba(255, 245, 242, 0.8)"
    text: "#ffffff"
    text-header: "#fafafa"
    text-title: "#000000"
    text-subtitle: "#111111"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#3273dc"
    link-hover: "#2e4053"
    background-image: "../assets/wallpaper-light.jpeg" # Change wallpaper.jpeg to the name of your own custom wallpaper!
  dark:
    highlight-primary: "#181C3A"
    highlight-secondary: "#181C3A"
    highlight-hover: "#1F2347"
    background: "#12152B"
    card-background: "rgba(24, 28, 58, 0.8)"
    text: "#eaeaea"
    text-header: "#7C71DD"
    text-title: "#fafafa"
    text-subtitle: "#8B8D9C"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#c1c1c1"
    link-hover: "#fafafa"
    background-image: "../assets/wallpaper.jpeg"

services:
  - name: "Server"
    icon: "fas fa-server"
    items:
      - name: "Portainer"
        logo: "assets/tools/portainer.png" # Change github.png to the name of your own custom icon!
        subtitle: "Gerenciador de container!"
        tag: "portainer"
        tagstyle: "is-primary" # This will display the is-primary color! Try changing it to; is-link, is-info, is-success, is-warning or is-danger!
        url: "http://portainer.cloud.arpa"
        target: "_blank"

  - name: "Network"
    icon: "fas fa-network-wired"
    items:
      - name: "PiHole"
        logo: "assets/tools/pihole.png"
        subtitle: "Gerenciador de DNS"
        tag: "pihole"
        tagstyle: "is-info"
        url: "http:/pihole.cloud.arpa"
        target: "_blank"
      - name: "Nginx Proxy Manager"
        logo: "assets/tools/nginx-proxy-manager.png"
        subtitle: "Gerenciador de Proxy"
        tag: "nginx-proxy-manager"
        tagstyle: "is-info"
        url: "http:/cloud.arpa:81"
        target: "_blank"
